[package]
name = "usync"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
ssh2 = "0.9"
url = "2.5"
tempfile = "3.10"

[dev-dependencies]
tempfile = "3.10"
